# Generated by Django 3.2.3 on 2021-05-24 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Architector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('date_of_birth', models.SmallIntegerField(default=0, verbose_name='Дата рождения')),
                ('date_of_death', models.SmallIntegerField(default=0, verbose_name='Дата смерти')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='architectors/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Архитектор',
                'verbose_name_plural': 'Архитекторы',
            },
        ),
        migrations.CreateModel(
            name='Architecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('main_photo', models.ImageField(upload_to='architecture/', verbose_name='Главное фото')),
                ('year', models.SmallIntegerField(default=2021, verbose_name='Дата появления')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
                ('budget', models.PositiveIntegerField(default=0, help_text='указывать сумму в долларах', verbose_name='Бюджет')),
                ('url', models.SlugField(max_length=130, unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('architectors', models.ManyToManyField(related_name='architector', to='arch_works.Architector', verbose_name='архитекторы')),
            ],
            options={
                'verbose_name': 'Архитектурный шедевр',
                'verbose_name_plural': 'Архитектурные шедевры',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Cтиль',
                'verbose_name_plural': 'Cтили',
            },
        ),
        migrations.CreateModel(
            name='ArchitectureShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='architecture_shots/', verbose_name='Изображение')),
                ('architecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arch_works.architecture', verbose_name='архитектура')),
            ],
            options={
                'verbose_name': 'Кадр',
                'verbose_name_plural': 'Кадры',
            },
        ),
        migrations.AddField(
            model_name='architecture',
            name='styles',
            field=models.ManyToManyField(to='arch_works.Style', verbose_name='стили'),
        ),
    ]
