# Generated by Django 3.2.3 on 2021-05-26 17:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('arch_works', '0002_auto_20210526_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='architector',
            name='url',
            field=models.SlugField(default=datetime.datetime(2021, 5, 26, 17, 42, 31, 767098, tzinfo=utc), max_length=160),
            preserve_default=False,
        ),
    ]
