# Generated by Django 3.2.3 on 2021-05-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_works', '0003_architector_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architector',
            name='url',
            field=models.SlugField(max_length=160, unique=True),
        ),
    ]
