# Generated by Django 3.2.3 on 2021-05-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_works', '0004_alter_architector_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='architector',
            name='country',
            field=models.CharField(default='No country', max_length=200, verbose_name='Страна'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='architecture',
            name='architectors',
            field=models.ManyToManyField(related_name='architectors', to='arch_works.Architector', verbose_name='архитекторы'),
        ),
    ]
