# Generated by Django 3.2.3 on 2021-05-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_works', '0005_auto_20210527_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='architector',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
        migrations.AddField(
            model_name='style',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
    ]
