# Generated by Django 3.2.3 on 2021-06-03 15:42

import arch_works.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_works', '0006_auto_20210531_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architecture',
            name='main_photo',
            field=models.ImageField(upload_to='architecture/', validators=[arch_works.models.validate_resolution_photo], verbose_name='Главное фото'),
        ),
    ]
