# Generated by Django 3.2.3 on 2021-06-04 09:04

import arch_works.custom_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_works', '0007_alter_architecture_main_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architector',
            name='image',
            field=models.ImageField(upload_to='architectors/', validators=[arch_works.custom_validators.validate_resolution_photo], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='style',
            name='image',
            field=models.ImageField(default='architecture_styles_images/default.jpg', upload_to='architecture_styles_images/', validators=[arch_works.custom_validators.validate_resolution_photo], verbose_name='Изображение'),
        ),
    ]
