# Generated by Django 3.2.3 on 2021-06-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='important',
            field=models.BooleanField(default=False, verbose_name='Важно'),
        ),
    ]
