# Generated by Django 3.2.3 on 2021-06-29 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_important'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsfile',
            old_name='blog',
            new_name='news',
        ),
        migrations.RenameField(
            model_name='newsshot',
            old_name='blog',
            new_name='news',
        ),
    ]
