# Generated by Django 3.2.3 on 2021-06-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Електронная почта')),
                ('facebook_link', models.CharField(blank=True, max_length=200, verbose_name='Facebook')),
                ('instagram_link', models.CharField(blank=True, max_length=200, verbose_name='Instagram')),
                ('telegram_link', models.CharField(blank=True, max_length=200, verbose_name='Telegram')),
                ('twitter_link', models.CharField(blank=True, max_length=200, verbose_name='Twitter')),
                ('youtube_link', models.CharField(blank=True, max_length=200, verbose_name='YouTube')),
                ('website', models.CharField(blank=True, max_length=200, verbose_name='Вебсайт')),
                ('iframe_map', models.CharField(blank=True, max_length=200, verbose_name='Карта')),
            ],
        ),
    ]
