# Generated by Django 3.2.3 on 2021-06-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Блок Контактов', 'verbose_name_plural': 'Блоки Контактов'},
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='iframe_map',
            field=models.CharField(blank=True, help_text="1.Зайдите в https://www.google.com/maps/ и выберите точное место вашей компании <br/> \n                                                                                    2.Нажмите на кнопку 'поделиться'. <br/>\n                                                                                    3.Выберите подпункт 'встраивание карт' и нажмите на кнопку 'копировать HTML'. <br/>\n                                                                                    4.Вставьте это значение в даное поле. ", max_length=500, verbose_name='Карта'),
        ),
    ]
