# Generated by Django 3.2.3 on 2021-06-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactemail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactemail',
            options={'verbose_name': 'Сообщение от пользователя', 'verbose_name_plural': 'Сообщения от пользователей'},
        ),
        migrations.AlterField(
            model_name='contactemail',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Е-mail'),
        ),
        migrations.AlterField(
            model_name='contactemail',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='contactemail',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя/никнейм'),
        ),
    ]
