# Generated by Django 3.2.3 on 2021-05-31 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_works', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshot',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
    ]
